name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ secrets.ENV }}
      CERT: ${{ secrets.CERT }}
      KEY: ${{ secrets.KEY }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
    steps:
      - uses: actions/checkout@v3
      # - name: Run build script
      #   run: /bin/bash ./deploy/build.sh
      - name: test1
        run: echo "$ENV" > ./.env

      - name: test2
        run: ls | grep ".env"

      - name: test3
        run: cat ./.env
